import {useState} from 'react'
import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
    const [text, setText] = useState<string>('')
    const [result, setResult] = useState<number>(0)
    const [showResult, setShowResult] = useState<boolean>(false)
    const [loading, setLoading] = useState<boolean>(false)

    const textSentimentAnalysis = async (e: any) => {
        e.preventDefault()
        if (text.length > 0) {
            setLoading(true)

            const formData = new FormData()
            formData.append('input', text)

            fetch('http://10.80.200.162:8000/api', {
                // input: text,
                method: 'POST',
                body: formData,
                headers: {
                    'Access-Control-Allow-Origin': '*',
                },
            })
                .then(res => res.json())
                .then(res => {
                    // getting the result of the prediction
                    const parsedPrediction = JSON.parse(res)
                    // parsing string to number
                    const prediction = Number(parsedPrediction.prediction)

                    // setting the state
                    setResult(prediction)
                    setShowResult(true)
                    setLoading(false)
                })
                .catch(err => {
                    alert('Something went wrong')
                    console.error('ERROR', err)
                    setLoading(false)
                })
        } else {
            alert('Please enter some text')
        }
    }

    const resetResult = () => {
        setShowResult(false)
        setText('')
        setResult(0)
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Sentiment Analysis</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>Welcome to Sentiment Analysis</h1>

                {!loading ? (
                    <p className={styles.description}>
                        Enter a sentence to analyze its sentiment
                    </p>
                ) : (
                    <p className={styles.description}>
                        <div className={styles.loader}></div>
                    </p>
                )}

                <form
                    className={styles.form}
                    onSubmit={e => textSentimentAnalysis(e)}>
                    <textarea
                        placeholder="Enter text here..."
                        className={`${styles.textarea}
						 ${
                             result > 0
                                 ? styles.positive
                                 : result < 0
                                 ? styles.negative
                                 : styles.neutral
                         }`}
                        value={text}
                        onChange={e => setText(e.target.value)}
                    />

                    <div>
                        <button type={'submit'} className={styles.button}>
                            Analyze
                        </button>

                        <button
                            type={'reset'}
                            className={`${styles.button} ${styles.reset}`}
                            onClick={resetResult}>
                            Reset
                        </button>
                    </div>
                </form>

                {showResult && (
                    <div>
                        <p
                            className={`${styles.description} ${
                                styles.highlight
                            } ${
                                result > 0
                                    ? styles.positive
                                    : result < 0
                                    ? styles.negative
                                    : styles.neutral
                            }`}>
                            {result > 0
                                ? 'The sentence is Positive...'
                                : result < 0
                                ? 'The sentence is Negative...'
                                : 'The sentence is Neutral...'}
                        </p>
                    </div>
                )}
            </main>

            <footer className={styles.footer}>Sentiment Analysis</footer>
        </div>
    )
}

export default Home
